// WebSocket message types based on PROTOCOL.md
export const MESSAGE_TYPES = {
  // Connection
  CONNECT: 'CONNECT',
  
  // Room Management
  LIST_ROOMS: 'LIST_ROOMS',
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  ADD_BOT: 'ADD_BOT',
  
  // Game Flow
  GAME_START: 'GAME_START',
  TURN_START: 'TURN_START',
  PLACE_TILE: 'PLACE_TILE',
  PLACE_MEEPLE: 'PLACE_MEEPLE',
  TURN_END: 'TURN_END',
  GAME_END: 'GAME_END',
  
  // State Synchronization
  ROOM_STATE: 'ROOM_STATE',
  GAME_STATE: 'GAME_STATE',
  PLAYER_UPDATE: 'PLAYER_UPDATE',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_UPDATE: 'ROOM_UPDATE',
  ROOMS_LIST: 'ROOMS_LIST',
  TILE_PLACED: 'TILE_PLACED',
  MEEPLE_PLACED: 'MEEPLE_PLACED',
  
  // System
  ERROR: 'ERROR',
  PING: 'PING',
  PONG: 'PONG',
  CONNECTED: 'CONNECTED'
};

export const CONNECTION_STATES = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  RECONNECTING: 'RECONNECTING',
  FAILED: 'FAILED'
};

export const GAME_PHASES = {
  LOBBY: 'LOBBY',
  WAITING: 'WAITING',
  PLAYING: 'PLAYING',
  FINISHED: 'FINISHED'
};

export const ERROR_CODES = {
  NOT_CONNECTED: 'NOT_CONNECTED',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  INVALID_PLACEMENT: 'INVALID_PLACEMENT',
  NO_MEEPLES: 'NO_MEEPLES'
};

export default MESSAGE_TYPES;
